spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: eventapp
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email

        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/proselyte

      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/proselyte

server:
  port: 8091
