spring.application.name=keycloakex1

app.security.oauth2-issuer-uri=http://localhost:8080/realms/demo
app.security.oauth2-jwk-uri=${app.security.oauth2-issuer-uri}/protocol/openid-connect/certs

server.port=8081
